---
output:
  pdf_document: default
  html_document: default
---
```{r Importing the necessary libraries, warning=FALSE}
# Importing the necessary libraries

library(dplyr)
library(ggplot2)
library(stringr)

```

```{r Preparing data, warning=FALSE}
#Preperaing the data

#Cleanup
rm(list=ls())
gc()

# Weather from chicago between 2000 and 2024 hourly
weather <- read.csv("weather_chicago_2001_2023.csv")

# Crimes from Chicago, from 2001 to 2023
# Deleting unnesessary columns from crimes (location etc.)
# crimes[,c(2,4,5,13:22)] <- NULL
# compressed to gz using gzip
# modified crimes without locations data
crimes <- read.csv("crimes_chicago_mod.csv.gz")

crimes <- crimes %>%
  mutate(Date = format(as.POSIXct(Date, format = "%m/%d/%Y %I:%M:%S %p"), 
                       "%Y-%m-%dT%H:%M:%S"),
         Hour = round((as.integer(substr(Date, 12, 13)) * 3600 +
                         as.integer(substr(Date, 15, 16)) * 60 +
                         as.integer(substr(Date, 18, 19))) %/% 3600), 
         #rouding time to just hour to match weather$time
         Date = sprintf("%sT%02d%s",substr(Date, 1, 10), Hour, ":00")) %>%
  rename(offense_category = Primary.Type, offense_description = Description)

#View(crimes)
# Creating usefull columns, then join
crimes <- crimes %>% right_join(weather, by = join_by(Date==time))
# right join, because for now it's better to keep the days when no crime happens
```


Crimes in Detroit

```{r Preparing the Detroit data, eval=FALSE, warning=FALSE, include=FALSE}
weather <- read.csv("weather_detroit_2000_2024.csv", skip=3)
#crimes_det <- read.csv("crimes_detroit.csv")
#crimes_det[,c(1,2,4,5,9,10,12,16:25)] <- NULL
#View(crimes_det)
#write.csv(crimes_det, "crimes_detroit_mod.csv", row.names = FALSE)
crimes <- read.csv("crimes_detroit_mod.csv.gz")

crimes <- crimes %>% rename(Date = incident_timestamp) %>%
  mutate(Date = format(as.POSIXct(Date, 
                        format = "%Y/%m/%d"), "%Y-%m-%d"),
         Date = sprintf("%sT%02d%s", Date, hour_of_day, ":00"))

crimes <- crimes %>% right_join(weather, by = join_by(Date==time))

```


```{r Checking how many are there different crimes types}
# Differet types of crimes should be analised separately

count_list <- list()

for(i in unique(crimes$offense_category)){
  count_list[[i]] <- sum(crimes$offense_category == i, na.rm=TRUE)
}
count_list_sorted <- count_list[order(unlist(count_list), decreasing = TRUE)]
types <- names(count_list_sorted)
counts <- unlist(count_list_sorted)
# Create a bar plot

#barplot(counts, names.arg = types, las = 2, 
#        col = ifelse(counts<mean(counts),"red","skyblue"),
#        main = "Counts of Crime Types", xlab = "Crime Types", ylab = "Count")


#ggplot(as.data.frame(types, counts), aes(x = reorder(types, -counts), y = counts, fill = counts > mean(counts))) +
#  geom_bar(stat = "identity") +
#  scale_fill_manual(values = c("TRUE" = "skyblue", "FALSE" = "red")) +
#  labs(x = "Rodzaje przestępstw", y = "Ilość") +
#  theme(axis.text.y = element_text(angle = 0, vjust = 1, hjust = 1))+
#  theme(axis.title.y = element_text(angle = 0, vjust = 0.5, hjust = 1)) +
#  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))


ggplot(as.data.frame(types, counts), aes(x = reorder(types, -counts), y = counts)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  labs(x = "Rodzaje przestępstw", y = "Ilość") +
  theme(axis.text.y = element_text(angle = 0, vjust = 1, hjust = 1)) +
  theme(axis.title.y = element_text(angle = 0, vjust = 0.5, hjust = 1)) +
  theme(axis.text.x = element_text(angle = 40, vjust = 1, hjust = 1))


```


```{r Plotting correlation between different crime types and weather}
#plotting for each crime type

count_list <- list()

for(i in unique(crimes$offense_category)){
  count_list[[i]] <- sum(crimes$offense_category == i, na.rm=TRUE)
}
count_list_sorted <- count_list[order(unlist(count_list), decreasing = TRUE)]


crime_types <- names(count_list_sorted)[1:20]

number_of_day_in_year <- as.POSIXlt(substr(crimes$Date,1,10), 
                                    format = "%Y-%m-%d")$yday
cut_min <- 0.05
cut_max <- 0.95
head(crimes$Date)
for(crimeType in crime_types){
  df <- crimes %>%
    mutate(Date = number_of_day_in_year %/% 7) %>%
    filter(offense_category == crimeType) %>%
    group_by(Date)%>%
    summarise(mean_temp = mean(temperature_2m...C.),
              mean_wind = mean(wind_speed_10m..km.h.),
              mean_precipitation = mean(precipitation..mm.),
              mean_cloud = mean(cloud_cover....),
              count = n()) %>%
    filter(between(count, quantile(count, c(cut_min, cut_max))[[1]],
                   quantile(count, c(cut_min, cut_max))[[2]])) #%>%
    #filter(between(mean_cloud, quantile(mean_cloud, c(cut_min, cut_max))[[1]], 
    #               quantile(mean_cloud, c(cut_min, cut_max))[[2]]))
  
  #var_cor <- df$mean_cloud
  
  print("")
  suma_cor = as.integer(0)
  for(j in colnames(df)[2:5]){
    df <- df %>% 
    filter(between(.data[[j]], quantile(.data[[j]], c(cut_min, cut_max))[[1]], 
                   quantile(.data[[j]], c(cut_min, cut_max))[[2]]))
    title <- sprintf("crime type: %s - %s rows: %d cor = %f", 
                     crimeType, j, dim(df)[1], 
                     cor(df[j], df$count, method = "pearson"))
    suma_cor = suma_cor + abs(cor(df[j], df$count, method = "pearson"))
    print(title)
    if(nrow(df)!=0){
      #plot(var_cor, df$count,las=2, main = title, 
      #     type="p", pch=16, col=rgb(0,0,0,0.3))
      #ggplot(as.data.frame(var_cor, df$count), aes(x = var_cor, y = df$count)) +
      #  geom_point(shape = 16, color = rgb(0, 0, 0, 0.5)) +
      #  labs(title = title, x = "var_cor", y = "Count") +
      #  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
      #plot(df$Date, df$count, main = paste(crimeType,"in year"), 
      #    type="l", pch=16, col=rgb(0,0,0,0.3))
      
      p <- ggplot(df, aes(x = .data[[j]], y = count)) +
        geom_point(shape = 16, color = rgb(0, 0, 0, 0.5)) +
        labs(title = title, x = j, y = "Count") +
        theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
      print(p)  # Explicitly print the plot
      
      # Optional: Create a time series plot
      #p_time_series <- ggplot(df, aes(x = Date, y = count)) +
      #  geom_line(color = rgb(0, 0, 0, 0.5)) +
      #  labs(title = paste(crimeType, "in Year"), x = "Day of the Year", y = "Count")
      #print(p_time_series) 
      
    }
  }
  print(suma_cor/4)
  
}
```

```{r Plotting correlation between different crime types and weather V2, eval=FALSE, include=FALSE}
#plotting for each crime type

count_list <- list()

for(i in unique(crimes$offense_category)[1:5]){
  count_list[[i]] <- sum(crimes$offense_category == i, na.rm=TRUE)
}
count_list_sorted <- count_list[order(unlist(count_list), decreasing = TRUE)]


crime_types <- names(count_list_sorted)[1:20]

number_of_day_in_year <- as.POSIXlt(substr(crimes$Date,1,10), 
                                    format = "%Y-%m-%d")$yday
cut_min <- 0.05
cut_max <- 0.95
for(crimeType in crime_types){
  df <- crimes %>%
      #mutate(Date = number_of_day_in_year) %>%
      filter(offense_category == crimeType)
  
  print("")
  for(j in colnames(crimes)[11:20]){
    
    #View(df)
    #colnames(df) 
    
    df_summary <- df %>%
      group_by(.data[[j]]) %>%
      summarise(count = n()) #%>%
    weather_summary <- weather %>%
      group_by(.data[[j]]) %>%
      summarise(count = n())
    plot(weather_summary)
    df_summary <- inner_join(df_summary, weather_summary, by = j) %>%
      mutate(count.x = count.x/count.y) %>%
      rename(count = count.x)
    
    
    #df_summary <- aggregate(df[[j]], by = list(df[[j]]), 
    #                      FUN = function(x) sum(!is.na(x)) / length(x))
    # Rename the columns for clarity
    #colnames(df_summary) <- c(j, "count")
    
    #filter(between(count, quantile(count, c(cut_min, cut_max))[[1]],
    #               quantile(count, c(cut_min, cut_max))[[2]]))%>% 
    #filter(between(.data[[j]], quantile(.data[[j]], c(cut_min, cut_max))[[1]], 
    #               quantile(.data[[j]], c(cut_min, cut_max))[[2]]))
    
    if(nrow(df)!=0){
      #plot(var_cor, df$count,las=2, main = title, 
      #     type="p", pch=16, col=rgb(0,0,0,0.3))
      #ggplot(as.data.frame(var_cor, df$count), aes(x = var_cor, y = df$count)) +
      #  geom_point(shape = 16, color = rgb(0, 0, 0, 0.5)) +
      #  labs(title = title, x = "var_cor", y = "Count") +
      #  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
      #plot(df$Date, df$count, main = paste(crimeType,"in year"), 
      #    type="l", pch=16, col=rgb(0,0,0,0.3))
      
      title <- sprintf("crime type: %s - %s rows: %d cor = %f", 
                     crimeType, j, nrow(df_summary), 
                     cor(df_summary[[j]], df_summary$count, method = "pearson"))
      print(title)
      
      # Generate scatter plot
      p <- ggplot(df_summary, aes(x = .data[[j]], y = count)) +
        geom_point(shape = 16, color = rgb(0, 0, 0, 0.5)) +
        labs(title = title, x = j, y = "Count") +
        theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
      print(p)  # Explicitly print the plot
    
    }
  }
}
```



```{r Analysing Narcotics crimes}

number_of_day_in_year <- as.POSIXlt(substr(crimes$Date,1,10), 
                                    format = "%Y-%m-%d")$yday
cut_min <- 0.05
cut_max <- 0.95

#crimeType <- "NARCOTICS" #Chicago
crimeType <- "STOLEN VEHICLE" #Detroit

print(unique(unlist(crimes %>% 
                      filter(offense_category == crimeType) %>% 
                      select(offense_description))))

#crimes <- crimes %>%s
#  mutate(offense_description = case_when(
#    offense_category == crimeType & 
#      str_detect(offense_description, "POSS") ~ "POSSESS",
#    offense_category == crimeType & 
#      ( str_detect(offense_description, "DELIVER") | 
#         str_detect(offense_description, "MANU")) ~ "MANU/DELIVER",
#    TRUE ~ offense_description))


differentCrimeDescritions <- crimes %>%
  filter(offense_category == crimeType) %>%
  group_by(offense_description) %>%
  summarise(count = n()) %>%
  arrange(desc(count))


ggplot(differentCrimeDescritions[1:15,], 
       aes(x = reorder(offense_description, -count), y = count)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  labs(title = paste("Count of", crimeType, "by Offense Description"),
       x = "Offense Description",
       y = "Count") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))



df_crimes <- crimes %>%
    mutate(Date = number_of_day_in_year) %>%
    filter(offense_category == crimeType)

for(i in differentCrimeDescritions$offense_description[1]){
  prepare_crimes <- df_crimes %>%
    filter(offense_description == i) %>%
    group_by(Date)%>%
    summarise(mean_temp = mean(temperature_2m...C.),
              mean_humidity = mean(relative_humidity_2m....),
              #mean_precipitation = mean(precipitation..mm.),
              mean_weather_code = mean(weather_code..wmo.code.),
              #mean_pressure = mean(pressure_msl..hPa.),
              mean_wind = mean(wind_speed_10m..km.h.),
              mean_cloud = mean(cloud_cover....),
              count = n())
  
  for(j in colnames(prepare_crimes)[2:6]){
    df_toPlot <- prepare_crimes %>%
      group_by(.data[[j]] %/% 1) %>%
      summarise(count = mean(count)) %>%
      filter(between(count, 
                     quantile(count, c(cut_min, cut_max))[[1]], 
                     quantile(count, c(cut_min, cut_max))[[2]]))
  
    colnames(df_toPlot)[1] <- "first_col"
    
    df_toPlot <- df_toPlot %>%
      filter(between(first_col, 
                       quantile(first_col, c(cut_min, cut_max))[[1]], 
                       quantile(first_col, c(cut_min, cut_max))[[2]]))
    
    title <- sprintf("%s:%s | %s , cor = %f", 
                     crimeType, i, j, 
                   cor(df_toPlot[1], df_toPlot$count, method = "pearson"))
    print(paste(title," rows:", nrow(df_toPlot)))
    
    p <- ggplot(df_toPlot, aes(x = first_col, y = count)) +
        geom_point(color = rgb(0, 0, 0, 1), shape = 16) +
        labs(x = paste(i,j), y = "Ilość") +
        theme(axis.text.y = element_text(angle = 0, vjust = 1, hjust = 1)) +
        theme(axis.title.y = element_text(angle = 0, vjust = 0.5, hjust = 1))
        #theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))
    
    print(p)
  }
}

```



```{r Analysing homicide crimes}

number_of_day_in_year <- as.POSIXlt(substr(crimes$Date,1,10), 
                                    format = "%Y-%m-%d")$yday
cut_min <- 0.05
cut_max <- 1

crimeType <- "HOMICIDE"

print(unique(unlist(crimes %>% 
                      filter(offense_category == crimeType) %>% 
                      select(offense_description))))

df_Homicide <- crimes %>%
    mutate(Date = number_of_day_in_year %/% 7) %>%
    filter(offense_category == crimeType) %>%
    filter(offense_description == "FIRST DEGREE MURDER") %>%
    group_by(Date)%>%
    summarise(mean_temp = mean(temperature_2m...C.),
              mean_wind = mean(wind_speed_10m..km.h.),
              #mean_precipitation = mean(precipitation..mm.),
              mean_cloud = mean(cloud_cover....),
              #mean_humidity = mean(relative_humidity_2m....),
              #mean_sur_pressure = mean(surface_pressure..hPa.),
              count = n()) %>%
    filter(between(count, 
                   quantile(count, c(cut_min, cut_max))[[1]], 
                   quantile(count, c(cut_min, cut_max))[[2]]))# %>%
    #filter(
    #  between(mean_temp, quantile(mean_temp, c(cut_min, cut_max))[1], quantile(mean_temp, c(cut_min, cut_max))[2]) &
    #  between(mean_wind, quantile(mean_wind, c(cut_min, cut_max))[1], quantile(mean_wind, c(cut_min, cut_max))[2]) &
      #between(mean_precipitation, quantile(mean_precipitation, c(cut_min, cut_max))[1], quantile(mean_precipitation, c(cut_min, cut_max))[2]) &
    #  between(mean_cloud, quantile(mean_cloud, c(cut_min, cut_max))[1], quantile(mean_cloud, c(cut_min, cut_max))[2]) 
      #& between(mean_humidity, quantile(mean_humidity, c(cut_min, cut_max))[1], quantile(mean_humidity, c(cut_min, cut_max))[2]) &
      #between(mean_sur_pressure, quantile(mean_sur_pressure, c(cut_min, cut_max))[1], quantile(mean_sur_pressure, c(cut_min, cut_max))[2]))


# Normalizing 
normalize <- function(x) {
  return((x - min(x)) / (max(x) - min(x)))
}

df_Homicide_normalized <- as.data.frame(lapply(df_Homicide, normalize))
df_Homicide_standardized <- scale(df_Homicide)
#write.csv(df_Homicide_normalized, 
#          "df_Homicide_normalized.csv", row.names = FALSE)
#write.csv(df_Homicide_standardized, 
#          "df_Homicide_standardized.csv", row.names = FALSE)


for (i in colnames(df_Homicide_normalized)[2:4]){
  title <- sprintf("%s:%s | %s , cor = %f", 
                   crimeType, "FIRST DEGREE MURDER", i, 
                 cor(df_Homicide[i], df_Homicide$count, method = "pearson"))
  print(paste(title," rows:", dim(df_Homicide)[1]))
  
  p <- ggplot(df_Homicide, aes(x = .data[[i]], y = count)) +
      geom_point(color = rgb(0, 0, 0, 1), shape = 16) +
      labs(x = "Zachmurzenie", y = "Ilość") +
      theme(axis.text.y = element_text(angle = 0, vjust = 1, hjust = 1)) +
      theme(axis.title.y = element_text(angle = 0, vjust = 0.5, hjust = 1))
      #theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))
  
  print(p)
  
}

```



```{r Analysing homicide crimes V2}

number_of_day_in_year <- as.POSIXlt(substr(crimes$Date,1,10), 
                                    format = "%Y-%m-%d")$yday
cut_min <- 0.1
cut_max <- 0.95

crimeType <- "HOMICIDE"

print(unique(unlist(crimes %>% 
                      filter(offense_category == crimeType) %>% 
                      select(offense_description))))

prepare_crimes <- crimes %>%
    mutate(Date = number_of_day_in_year) %>%
    filter(offense_category == crimeType) %>%
    filter(offense_description == "FIRST DEGREE MURDER") %>%
    group_by(Date)%>%
    summarise(mean_temp = mean(temperature_2m...C.),
              mean_temp_app = mean(apparent_temperature...C.),
              mean_humidity = mean(relative_humidity_2m....),
              mean_precipitation = mean(precipitation..mm.),
              mean_weather_code = mean(weather_code..wmo.code.),
              mean_sur_pressure = mean(pressure_msl..hPa.),
              mean_wind = mean(wind_speed_10m..km.h.),
              mean_cloud = mean(cloud_cover....),
              count = n())


for(i in colnames(prepare_crimes)[2:9]){
  df_Homicide <- prepare_crimes %>%
      group_by(.data[[i]] %/% 1) %>%
      summarise(count = mean(count)) %>%
      filter(between(count, 
                     quantile(count, c(cut_min, cut_max))[[1]], 
                     quantile(count, c(cut_min, cut_max))[[2]]))
  
  colnames(df_Homicide)[1] <- "first_col"
  
  df_Homicide <- df_Homicide %>%
    filter(between(first_col, 
                     quantile(first_col, c(cut_min, cut_max))[[1]], 
                     quantile(first_col, c(cut_min, cut_max))[[2]]))
  
  title <- sprintf("%s:%s | %s , cor = %f", 
                   crimeType, "FIRST DEGREE MURDER", i, 
                 cor(df_Homicide[1], df_Homicide$count, method = "pearson"))
  print(paste(title," rows:", nrow(df_Homicide)))
  
  p <- ggplot(df_Homicide, aes(x = first_col, y = count)) +
      geom_point(color = rgb(0, 0, 0, 1), shape = 16) +
      labs(x = i, y = "Ilość") +
      theme(axis.text.y = element_text(angle = 0, vjust = 1, hjust = 1)) +
      theme(axis.title.y = element_text(angle = 0, vjust = 0.5, hjust = 1))
      #theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))
  
  print(p)

}

```